module1-task-2
htmlacademy-yii/211794-task-force-1 pull request #2
Opened 2020-07-04 22:56 UTC by AlexHomylev

2020-07-06 13:29 UTC, raidkon requested changes
Добавь composer.json и укажи какую версию php используешь.

2020-07-06 13:29 UTC, raidkon commented on php/Task.php
> +    public $statusMap = [
Зачем под это каждый раз при новом экземпляре выделять память, вынеси справочники в статичные методы.

2020-07-06 14:11 UTC, AlexHomylev commented on php/Task.php
> +    public $statusMap = [
Согласен, поправил.

2020-07-07 13:02 UTC, raidkon requested changes

2020-07-07 13:02 UTC, raidkon commented on composer.json
> +    "require": {}
Какая версия пхп используется?

2020-07-08 04:34 UTC, AlexHomylev commented on composer.json
> +    "require": {}
Использую версию 7.2

2020-07-09 23:02 UTC, merged