module1-task3
htmlacademy-yii/211794-task-force-1 pull request #3
Opened 2020-07-10 17:46 UTC by AlexHomylev

2020-07-11 22:15 UTC, raidkon requested changes

2020-07-11 22:15 UTC, raidkon commented on composer.json
> +        "src/models/Task.php"
зачем ты вручную прописываешь классы? это равно сильно ручному подключению. задача автоматизировать подгрузку.

2020-07-11 22:15 UTC, raidkon commented on composer.json
> +        "211794-task-force-1\\": "src"
Надо сделать вместо 211794-task-force-1 какой пространство имен которое после будет использоваться в проекте, например app

2020-07-13 07:39 UTC, AlexHomylev commented on composer.json
> +        "src/models/Task.php"
Мне тоже это показалось немного странным когда гайды читал, я вроде поправил, если опять что то не так, обьясни для как для дураков как это правильно реализовать.

2020-07-13 08:12 UTC, AlexHomylev commented on composer.json
> +        "211794-task-force-1\\": "src"
Поправил

2020-07-13 10:53 UTC, raidkon commented
Сам файл Task.php лежит не в неймспейсе, его туда необходимо положить.

2020-07-14 10:27 UTC, merged